// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwfquywkobwnhtaiddef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3ZnF1eXdrb2J3bmh0YWlkZGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDM2NjYsImV4cCI6MjA3Mzc3OTY2Nn0.AQzzoKdLlisaYnFd0XdcVw7UROzEtrpS94RUxHTXmME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});